version: '3'
services:
 csv_collector:
  image: p/p
  container_name: csv_collector
  volumes:
   - /home/fbenayas/Escritorio/data/csv_collector/csv:/home/csv
  depends_on:
   - elasticsearch
  networks:
   - el
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  container_name: elasticsearch
  volumes:
   - /home/fbenayas/Escritorio/data/data:/usr/share/elasticsearch/data
   - /home/fbenayas/Escritorio/data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  environment:
   - http.host=0.0.0.0
   - transport.host=127.0.0.1
  ports:
   - 9200:9200
   - 9300:9300
  networks:
   - el
networks:
 el:
  driver: bridge