version: '3'
services:
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  container_name: elasticsearch
  volumes:
   - ./data:/usr/share/elasticsearch/data
   - ./data/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  environment:
   - http.host=0.0.0.0
   - transport.host=127.0.0.1
  ports:
   - 9200:9200
   - 9300:9300
  networks:
   - el
 csv_collector:
  image: registry.cluster.gsi.dit.upm.es/sdn/data-processor:1.0
  container_name: csv_collector
  depends_on:
   - elasticsearch
  networks:
   - el
  tty: true
networks:
 el:
  driver: bridge
