version: '3'
services:
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  container_name: elasticsearch
  volumes:
   - /home/fbenayas/Downloads/data:/usr/share/elasticsearch/data
   - /home/fbenayas/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  environment:
   - http.host=0.0.0.0
   - transport.host=127.0.0.1
  ports:
   - 9200:9200
   - 9300:9300
  networks:
   - el
 csv_collector:
  image: csv/prueba
  container_name: csv_collector
  depends_on:
   - elasticsearch
  networks:
   - el
  tty: true
 kibana:
  image: docker.elastic.co/kibana/kibana:5.5.1
  container_name: kibana
  networks:
   - el
  ports:
   - 5601:5601
  depends_on:
   - elasticsearch
networks:
 el:
  driver: bridge
